-- Enable UUID extension for generating IDs
create extension if not exists "uuid-ossp";

-- 1. Users Table (Using text ID to support existing mock internal IDs)
create table public.users (
  id text primary key, 
  email text unique not null,
  name text not null,
  role text check (role in ('exporter', 'qa_agency', 'admin', 'importer')) not null,
  company text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Batches Table
create table public.batches (
  id uuid default uuid_generate_v4() primary key,
  exporter_name text not null,
  product_type text not null,
  quantity text not null,
  farm_location text not null,
  destination_country text not null,
  notes text,
  status text check (status in ('SUBMITTED', 'INSPECTED', 'CERTIFIED', 'REJECTED')) default 'SUBMITTED',
  submitted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  exporter_id text references public.users(id),
  inspection_data jsonb,
  documents text[] -- Array of strings for document URLs/Hashes
);

-- 3. Certificates Table
create table public.certificates (
  id text primary key, -- Certificate IDs are often custom strings/hashes
  batch_id uuid references public.batches(id) not null,
  issued_at timestamp with time zone default timezone('utc'::text, now()) not null,
  valid_until timestamp with time zone not null,
  status text check (status in ('VALID', 'REVOKED', 'EXPIRED')) default 'VALID',
  vc_data jsonb,
  metadata jsonb,
  issuer text default 'National Quality Agency',
  hash text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Audit Logs Table
create table public.audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  user_id text references public.users(id),
  details jsonb,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Row Level Security Policies
-- Enable RLS
alter table public.users enable row level security;
alter table public.batches enable row level security;
alter table public.certificates enable row level security;
alter table public.audit_logs enable row level security;

-- Create blanket policies to allow all operations (for development/demo purposes)
create policy "Enable all access for all users" on public.users for all using (true) with check (true);
create policy "Enable all access for all users" on public.batches for all using (true) with check (true);
create policy "Enable all access for all users" on public.certificates for all using (true) with check (true);
create policy "Enable all access for all users" on public.audit_logs for all using (true) with check (true);

-- 6. Seed Data (Essential for app defaults)
insert into public.users (id, email, name, role, company) values
  ('1', 'exporter@demo.com', 'Demo Exporter', 'exporter', 'Green Valley Farms'),
  ('2', 'qa@demo.com', 'QA Officer', 'qa_agency', 'Global Standards Agency'),
  ('3', 'importer@demo.com', 'Demo Importer', 'importer', 'Fresh Imports Co'),
  ('4', 'admin@demo.com', 'System Admin', 'admin', 'AgriPass System');

-- Optional: Seed a demo batch
insert into public.batches (exporter_name, product_type, quantity, farm_location, destination_country, status, exporter_id)
values
  ('Demo Exporter', 'Apples', '1000 kg', 'California, USA', 'Japan', 'SUBMITTED', '1');
